VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "LayoutInfo"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
'Struct
Option Explicit

'===============================================================================

Public NumHeight As Long
Public NumWidth As Long
Public Rotate As Boolean
Public Space As Double
